########################################
# Bonita redirects
########################################
[[redirects]]
  from = "/bonita/latest/*"
# TODO if we want proxy/rewrite instead, add status = 200 (https://docs.netlify.com/routing/redirects/rewrites-proxies/)
  to = "/bonita/2021.1/:splat"

[[redirects]]
  from = "/bonita/"
  to = "/bonita/2021.1/"

# Special redirect after introduction of Bonita branding version
[[redirects]]
  from = "/bonita/7.12/*"
  to = "/bonita/2021.1/:splat"


########################################
# BCD redirects
########################################
[[redirects]]
from = "/bcd/latest/*"
# TODO if we want proxy/rewrite instead, add status = 200 (https://docs.netlify.com/routing/redirects/rewrites-proxies/)
to = "/bcd/3.4/:splat"

[[redirects]]
from = "/bcd/"
to = "/bcd/3.4/"


########################################
# BICI redirects
########################################
[[redirects]]
from = "/bici/"
to = "/bici/latest/"

[[redirects]]
from = "/bici/1.0/*"
to = "/bici/latest/:splat"

[[redirects]]
from = "/bici/1.1/*"
to = "/bici/latest/:splat"

[[redirects]]
from = "/bici/1.2/*"
to = "/bici/latest/:splat"

[[redirects]]
from = "/bici/1.3/*"
to = "/bici/latest/:splat"

[[redirects]]
from = "/ici/:version/*"
to = "/bici/latest/:splat"



########################################
# Bonita Cloud redirects
########################################
[[redirects]]
from = "/cloud/"
to = "/cloud/latest/"

########################################
# Bonita Legacy Doc redirects
########################################
[[redirects]]
from = "/6.x-7.2/*"
to = "https://documentation-legacy.bonitasoft.com/6.x-7.2/:splat"


