name: Generate documentation

on:
  workflow_dispatch:
   inputs:
      branch:
        required: false
        description: 'Branch of component'
      component:
        required: false
        description: 'Name of component which triggers the build'
  pull_request:
    branches:
      - master
    paths:
      - 'resources/*'
      - 'antora-playbook.yml'
      - '.github/workflows/generate-documentation.yml'
  push:
    branches:
      - master
    paths:
      - 'resources/*'
      - 'antora-playbook.yml'
      - '.github/workflows/generate-documentation.yml'
jobs:
  generate_doc:
    runs-on: ubuntu-20.04
    env:
      GOOGLE_ANALYTICS_KEY: G-7LLM509FEH
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build docs PR
        if: github.event_name == 'pull_request'
        run: npm run local:build-static
      - name: Build docs
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: GOOGLE_ANALYTICS_KEY=${{env.GOOGLE_ANALYTICS_KEY}} npm run build
      - name: Zip docs
        run: |
          cd build/site/
          zip -q -r ../site .
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation-${{github.sha}}
          path: build/site.zip

  push_to_gh_pages:
    # only when 'on push/workflow_dispatch to master'
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&  github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: generate_doc
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: documentation-${{github.sha}}
      - name: Unzip Docs
        run: |
          echo "Unzipping docs..."
          unzip -q site.zip
          rm -rf site.zip
          echo "Docs unzipped"
          ls -lh
      - name: Create commit message if no component defined
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.component == ''
        run:
          echo "commit_message=deploy ${{github.sha}} from manual request" >> $GITHUB_ENV
      - name: Create commit message if component defined
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.component != ''
        run:
          echo "commit_message=deploy ${{ github.event.inputs.component }} ${{ github.event.inputs.branch }} update" >> $GITHUB_ENV
      - name: Create commit message if push
        if: github.event_name == 'push'
        run:
          echo "commit_message=deploy ${{ github.sha }}" >> $GITHUB_ENV
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          user_name: 'bonita-ci'
          user_email: 'hudson.mailer@bonitasoft.com'
          full_commit_message: ${{ env.commit_message }}

  deploy_to_netlify:
    # TODO restore push only (as for gh-pages)
    if: (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-20.04
    needs: generate_doc
    steps:
      - uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: documentation-${{github.sha}}
      - name: Unzip Docs
        run: |
          echo "Unzipping docs..."
          mkdir site/
          unzip -q site.zip -d site/
          echo "Docs unzipped"
          ls -lh
      - name: Create deploy message if no component defined
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.component == ''
        run:
          echo "deploy_message=Deploy ${{github.sha}} from manual request" >> $GITHUB_ENV
      - name: Create deploy message if component defined
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.component != ''
        run:
          echo "deploy_message=Deploy ${{ github.event.inputs.component }} ${{ github.event.inputs.branch }} update" >> $GITHUB_ENV
      - name: Create deploy message if push or pull request
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run:
          echo "deploy_message=Deploy ${{ github.sha }}" >> $GITHUB_ENV
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './site'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ env.deploy_message }}
          enable-pull-request-comment: false
          enable-commit-comment: true
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
